/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: .\op.i

package opEx

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
typedef long long swig_type_24;
typedef long long swig_type_25;
typedef long long swig_type_26;
typedef long long swig_type_27;
typedef long long swig_type_28;
typedef long long swig_type_29;
typedef long long swig_type_30;
typedef long long swig_type_31;
typedef long long swig_type_32;
typedef long long swig_type_33;
typedef long long swig_type_34;
typedef long long swig_type_35;
typedef long long swig_type_36;
typedef long long swig_type_37;
typedef long long swig_type_38;
typedef long long swig_type_39;
typedef long long swig_type_40;
typedef long long swig_type_41;
typedef long long swig_type_42;
typedef long long swig_type_43;
typedef long long swig_type_44;
typedef long long swig_type_45;
typedef long long swig_type_46;
typedef long long swig_type_47;
typedef long long swig_type_48;
typedef long long swig_type_49;
typedef long long swig_type_50;
typedef long long swig_type_51;
typedef long long swig_type_52;
typedef long long swig_type_53;
typedef long long swig_type_54;
typedef long long swig_type_55;
typedef long long swig_type_56;
typedef long long swig_type_57;
typedef long long swig_type_58;
typedef long long swig_type_59;
typedef long long swig_type_60;
typedef long long swig_type_61;
typedef long long swig_type_62;
typedef long long swig_type_63;
typedef long long swig_type_64;
typedef long long swig_type_65;
typedef long long swig_type_66;
typedef long long swig_type_67;
typedef long long swig_type_68;
typedef long long swig_type_69;
typedef long long swig_type_70;
typedef long long swig_type_71;
typedef long long swig_type_72;
typedef long long swig_type_73;
typedef long long swig_type_74;
typedef long long swig_type_75;
typedef long long swig_type_76;
typedef long long swig_type_77;
typedef long long swig_type_78;
typedef long long swig_type_79;
typedef long long swig_type_80;
typedef long long swig_type_81;
typedef long long swig_type_82;
typedef long long swig_type_83;
typedef long long swig_type_84;
typedef long long swig_type_85;
typedef long long swig_type_86;
typedef long long swig_type_87;
typedef long long swig_type_88;
typedef long long swig_type_89;
typedef long long swig_type_90;
typedef long long swig_type_91;
typedef long long swig_type_92;
typedef long long swig_type_93;
typedef long long swig_type_94;
typedef long long swig_type_95;
typedef long long swig_type_96;
typedef long long swig_type_97;
typedef long long swig_type_98;
typedef long long swig_type_99;
typedef long long swig_type_100;
typedef long long swig_type_101;
typedef long long swig_type_102;
typedef long long swig_type_103;
typedef long long swig_type_104;
typedef long long swig_type_105;
typedef long long swig_type_106;
typedef long long swig_type_107;
typedef long long swig_type_108;
typedef long long swig_type_109;
typedef long long swig_type_110;
typedef long long swig_type_111;
typedef long long swig_type_112;
typedef long long swig_type_113;
typedef long long swig_type_114;
typedef long long swig_type_115;
typedef long long swig_type_116;
typedef long long swig_type_117;
typedef long long swig_type_118;
typedef long long swig_type_119;
typedef long long swig_type_120;
typedef long long swig_type_121;
typedef long long swig_type_122;
typedef long long swig_type_123;
typedef long long swig_type_124;
typedef long long swig_type_125;
typedef long long swig_type_126;
typedef long long swig_type_127;
typedef long long swig_type_128;
typedef long long swig_type_129;
typedef long long swig_type_130;
typedef long long swig_type_131;
typedef long long swig_type_132;
typedef long long swig_type_133;
typedef long long swig_type_134;
typedef long long swig_type_135;
typedef long long swig_type_136;
typedef long long swig_type_137;
typedef long long swig_type_138;
typedef long long swig_type_139;
typedef long long swig_type_140;
typedef long long swig_type_141;
typedef long long swig_type_142;
typedef long long swig_type_143;
typedef long long swig_type_144;
typedef long long swig_type_145;
typedef long long swig_type_146;
typedef long long swig_type_147;
typedef long long swig_type_148;
typedef long long swig_type_149;
typedef long long swig_type_150;
typedef long long swig_type_151;
typedef long long swig_type_152;
typedef long long swig_type_153;
typedef long long swig_type_154;
typedef long long swig_type_155;
typedef long long swig_type_156;
typedef long long swig_type_157;
typedef long long swig_type_158;
typedef long long swig_type_159;
typedef long long swig_type_160;
typedef long long swig_type_161;
typedef long long swig_type_162;
typedef long long swig_type_163;
typedef long long swig_type_164;
typedef long long swig_type_165;
typedef long long swig_type_166;
typedef long long swig_type_167;
typedef long long swig_type_168;
extern void _wrap_Swig_free_opEx_7bb69c4307a7cd11(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_opEx_7bb69c4307a7cd11(swig_intgo arg1);
extern uintptr_t _wrap_new_libop_opEx_7bb69c4307a7cd11(void);
extern void _wrap_delete_libop_opEx_7bb69c4307a7cd11(uintptr_t arg1);
extern uintptr_t _wrap_libop_Ver_opEx_7bb69c4307a7cd11(uintptr_t arg1);
extern void _wrap_libop_SetPath_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_GetPath_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_libop_GetBasePath_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_libop_GetID_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_GetLastError_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_SetShowErrorMsg_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_1 arg2, swig_voidp arg3);
extern void _wrap_libop_Sleep_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_2 arg2, swig_voidp arg3);
extern void _wrap_libop_InjectDll_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_voidp arg4);
extern void _wrap_libop_EnablePicCache_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_3 arg2, swig_voidp arg3);
extern void _wrap_libop_CapturePre_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_AStarFindPath_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_4 arg2, swig_type_5 arg3, uintptr_t arg4, swig_type_6 arg5, swig_type_7 arg6, swig_type_8 arg7, swig_type_9 arg8, uintptr_t arg9);
extern void _wrap_libop_FindNearestPos_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_type_10 arg3, swig_type_11 arg4, swig_type_12 arg5, uintptr_t arg6);
extern void _wrap_libop_EnumWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_13 arg2, uintptr_t arg3, uintptr_t arg4, swig_type_14 arg5, uintptr_t arg6);
extern void _wrap_libop_EnumWindowByProcess_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, swig_type_15 arg5, uintptr_t arg6);
extern void _wrap_libop_EnumProcess_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_libop_ClientToScreen_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_16 arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5);
extern void _wrap_libop_FindWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_voidp arg4);
extern void _wrap_libop_FindWindowByProcess_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, swig_voidp arg5);
extern void _wrap_libop_FindWindowByProcessId_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_17 arg2, uintptr_t arg3, uintptr_t arg4, swig_voidp arg5);
extern void _wrap_libop_FindWindowEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_18 arg2, uintptr_t arg3, uintptr_t arg4, swig_voidp arg5);
extern void _wrap_libop_GetClientRect_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_19 arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7);
extern void _wrap_libop_GetClientSize_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_20 arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5);
extern void _wrap_libop_GetForegroundFocus_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_GetForegroundWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_GetMousePointWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_GetPointWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_21 arg2, swig_type_22 arg3, swig_voidp arg4);
extern void _wrap_libop_GetProcessInfo_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_23 arg2, uintptr_t arg3);
extern void _wrap_libop_GetSpecialWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_24 arg2, swig_voidp arg3);
extern void _wrap_libop_GetWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_25 arg2, swig_type_26 arg3, swig_voidp arg4);
extern void _wrap_libop_GetWindowClass_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_27 arg2, uintptr_t arg3);
extern void _wrap_libop_GetWindowProcessId_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_28 arg2, swig_voidp arg3);
extern void _wrap_libop_GetWindowProcessPath_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_29 arg2, uintptr_t arg3);
extern void _wrap_libop_GetWindowRect_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_30 arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5, swig_voidp arg6, swig_voidp arg7);
extern void _wrap_libop_GetWindowState_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_31 arg2, swig_type_32 arg3, swig_voidp arg4);
extern void _wrap_libop_GetWindowTitle_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_33 arg2, uintptr_t arg3);
extern void _wrap_libop_MoveWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_34 arg2, swig_type_35 arg3, swig_type_36 arg4, swig_voidp arg5);
extern void _wrap_libop_ScreenToClient_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_37 arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5);
extern void _wrap_libop_SendPaste_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_38 arg2, swig_voidp arg3);
extern void _wrap_libop_SetClientSize_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_39 arg2, swig_type_40 arg3, swig_type_41 arg4, swig_voidp arg5);
extern void _wrap_libop_SetWindowState_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_42 arg2, swig_type_43 arg3, swig_voidp arg4);
extern void _wrap_libop_SetWindowSize_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_44 arg2, swig_type_45 arg3, swig_type_46 arg4, swig_voidp arg5);
extern void _wrap_libop_SetWindowText_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_47 arg2, uintptr_t arg3, swig_voidp arg4);
extern void _wrap_libop_SetWindowTransparent_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_48 arg2, swig_type_49 arg3, swig_voidp arg4);
extern void _wrap_libop_SendString_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_50 arg2, uintptr_t arg3, swig_voidp arg4);
extern void _wrap_libop_SendStringIme_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_51 arg2, uintptr_t arg3, swig_voidp arg4);
extern void _wrap_libop_RunApp_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_type_52 arg3, swig_voidp arg4);
extern void _wrap_libop_WinExec_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_type_53 arg3, swig_voidp arg4);
extern void _wrap_libop_GetCmdStr_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_type_54 arg3, uintptr_t arg4);
extern void _wrap_libop_BindWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_55 arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5, swig_type_56 arg6, swig_voidp arg7);
extern void _wrap_libop_UnBindWindow_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_GetCursorPos_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3, swig_voidp arg4);
extern void _wrap_libop_MoveR_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_57 arg2, swig_type_58 arg3, swig_voidp arg4);
extern void _wrap_libop_MoveTo_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_59 arg2, swig_type_60 arg3, swig_voidp arg4);
extern void _wrap_libop_MoveToEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_61 arg2, swig_type_62 arg3, swig_type_63 arg4, swig_type_64 arg5, swig_voidp arg6);
extern void _wrap_libop_LeftClick_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_LeftDoubleClick_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_LeftDown_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_LeftUp_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_MiddleClick_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_MiddleDown_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_MiddleUp_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_RightClick_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_RightDown_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_RightUp_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_WheelDown_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_WheelUp_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_libop_GetKeyState_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_65 arg2, swig_voidp arg3);
extern void _wrap_libop_KeyDown_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_66 arg2, swig_voidp arg3);
extern void _wrap_libop_KeyDownChar_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_KeyUp_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_67 arg2, swig_voidp arg3);
extern void _wrap_libop_KeyUpChar_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_WaitKey_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_68 arg2, swig_type_69 arg3, swig_voidp arg4);
extern void _wrap_libop_KeyPress_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_70 arg2, swig_voidp arg3);
extern void _wrap_libop_KeyPressChar_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_Capture_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_71 arg2, swig_type_72 arg3, swig_type_73 arg4, swig_type_74 arg5, uintptr_t arg6, swig_voidp arg7);
extern void _wrap_libop_CmpColor_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_75 arg2, swig_type_76 arg3, uintptr_t arg4, double arg5, swig_voidp arg6);
extern void _wrap_libop_FindColor_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_77 arg2, swig_type_78 arg3, swig_type_79 arg4, swig_type_80 arg5, uintptr_t arg6, double arg7, swig_type_81 arg8, swig_voidp arg9, swig_voidp arg10, swig_voidp arg11);
extern void _wrap_libop_FindColorEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_82 arg2, swig_type_83 arg3, swig_type_84 arg4, swig_type_85 arg5, uintptr_t arg6, double arg7, swig_type_86 arg8, uintptr_t arg9);
extern void _wrap_libop_FindMultiColor_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_87 arg2, swig_type_88 arg3, swig_type_89 arg4, swig_type_90 arg5, uintptr_t arg6, uintptr_t arg7, double arg8, swig_type_91 arg9, swig_voidp arg10, swig_voidp arg11, swig_voidp arg12);
extern void _wrap_libop_FindMultiColorEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_92 arg2, swig_type_93 arg3, swig_type_94 arg4, swig_type_95 arg5, uintptr_t arg6, uintptr_t arg7, double arg8, swig_type_96 arg9, uintptr_t arg10);
extern void _wrap_libop_FindPic_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_97 arg2, swig_type_98 arg3, swig_type_99 arg4, swig_type_100 arg5, uintptr_t arg6, uintptr_t arg7, double arg8, swig_type_101 arg9, swig_voidp arg10, swig_voidp arg11, swig_voidp arg12);
extern void _wrap_libop_FindPicEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_102 arg2, swig_type_103 arg3, swig_type_104 arg4, swig_type_105 arg5, uintptr_t arg6, uintptr_t arg7, double arg8, swig_type_106 arg9, uintptr_t arg10);
extern void _wrap_libop_FindPicExS_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_107 arg2, swig_type_108 arg3, swig_type_109 arg4, swig_type_110 arg5, uintptr_t arg6, uintptr_t arg7, double arg8, swig_type_111 arg9, uintptr_t arg10);
extern void _wrap_libop_FindColorBlock_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_112 arg2, swig_type_113 arg3, swig_type_114 arg4, swig_type_115 arg5, uintptr_t arg6, double arg7, swig_type_116 arg8, swig_type_117 arg9, swig_type_118 arg10, swig_voidp arg11, swig_voidp arg12, swig_voidp arg13);
extern void _wrap_libop_FindColorBlockEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_119 arg2, swig_type_120 arg3, swig_type_121 arg4, swig_type_122 arg5, uintptr_t arg6, double arg7, swig_type_123 arg8, swig_type_124 arg9, swig_type_125 arg10, uintptr_t arg11);
extern void _wrap_libop_GetColor_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_126 arg2, swig_type_127 arg3, uintptr_t arg4);
extern void _wrap_libop_SetDisplayInput_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_LoadPic_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_FreePic_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, swig_voidp arg3);
extern void _wrap_libop_LoadMemPic_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, swig_type_128 arg4, swig_voidp arg5);
extern void _wrap_libop_GetScreenData_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_129 arg2, swig_type_130 arg3, swig_type_131 arg4, swig_type_132 arg5, swig_voidp arg6, swig_voidp arg7);
extern void _wrap_libop_GetScreenDataBmp_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_133 arg2, swig_type_134 arg3, swig_type_135 arg4, swig_type_136 arg5, swig_voidp arg6, swig_voidp arg7, swig_voidp arg8);
extern void _wrap_libop_GetScreenFrameInfo_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3);
extern void _wrap_libop_MatchPicName_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern void _wrap_libop_SetDict_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_137 arg2, uintptr_t arg3, swig_voidp arg4);
extern void _wrap_libop_SetMemDict_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_138 arg2, uintptr_t arg3, swig_type_139 arg4, swig_voidp arg5);
extern void _wrap_libop_UseDict_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_140 arg2, swig_voidp arg3);
extern void _wrap_libop_Ocr_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_141 arg2, swig_type_142 arg3, swig_type_143 arg4, swig_type_144 arg5, uintptr_t arg6, double arg7, uintptr_t arg8);
extern void _wrap_libop_OcrEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_145 arg2, swig_type_146 arg3, swig_type_147 arg4, swig_type_148 arg5, uintptr_t arg6, double arg7, uintptr_t arg8);
extern void _wrap_libop_FindStr_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_149 arg2, swig_type_150 arg3, swig_type_151 arg4, swig_type_152 arg5, uintptr_t arg6, uintptr_t arg7, double arg8, swig_voidp arg9, swig_voidp arg10, swig_voidp arg11);
extern void _wrap_libop_FindStrEx_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_153 arg2, swig_type_154 arg3, swig_type_155 arg4, swig_type_156 arg5, uintptr_t arg6, uintptr_t arg7, double arg8, uintptr_t arg9);
extern void _wrap_libop_OcrAuto_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_157 arg2, swig_type_158 arg3, swig_type_159 arg4, swig_type_160 arg5, double arg6, uintptr_t arg7);
extern void _wrap_libop_OcrFromFile_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, double arg4, uintptr_t arg5);
extern void _wrap_libop_OcrAutoFromFile_opEx_7bb69c4307a7cd11(uintptr_t arg1, uintptr_t arg2, double arg3, uintptr_t arg4);
extern void _wrap_libop_FindLine_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_161 arg2, swig_type_162 arg3, swig_type_163 arg4, swig_type_164 arg5, uintptr_t arg6, double arg7, uintptr_t arg8);
extern void _wrap_libop_WriteData_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_165 arg2, uintptr_t arg3, uintptr_t arg4, swig_type_166 arg5, swig_voidp arg6);
extern void _wrap_libop_ReadData_opEx_7bb69c4307a7cd11(uintptr_t arg1, swig_type_167 arg2, uintptr_t arg3, swig_type_168 arg4, uintptr_t arg5);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_opEx_7bb69c4307a7cd11(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrLibop uintptr

func (p SwigcptrLibop) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLibop) SwigIsLibop() {
}

func NewLibop() (_swig_ret Libop) {
	var swig_r Libop
	swig_r = (Libop)(SwigcptrLibop(C._wrap_new_libop_opEx_7bb69c4307a7cd11()))
	return swig_r
}

func DeleteLibop(arg1 Libop) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_libop_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrLibop) Ver() (_swig_ret Std_wstring) {
	var swig_r Std_wstring
	_swig_i_0 := arg1
	swig_r = (Std_wstring)(SwigcptrStd_wstring(C._wrap_libop_Ver_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrLibop) SetPath(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_SetPath_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) GetPath(arg2 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_libop_GetPath_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetBasePath(arg2 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_libop_GetBasePath_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetID(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_GetID_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetLastError(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_GetLastError_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) SetShowErrorMsg(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_SetShowErrorMsg_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) Sleep(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_Sleep_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_2(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) InjectDll(arg2 Wchar_t, arg3 Wchar_t, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	C._wrap_libop_InjectDll_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) EnablePicCache(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_EnablePicCache_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_3(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) CapturePre(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_CapturePre_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) AStarFindPath(arg2 int64, arg3 int64, arg4 Wchar_t, arg5 int64, arg6 int64, arg7 int64, arg8 int64, arg9 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9.Swigcptr()
	C._wrap_libop_AStarFindPath_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1), C.swig_type_5(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_type_6(_swig_i_4), C.swig_type_7(_swig_i_5), C.swig_type_8(_swig_i_6), C.swig_type_9(_swig_i_7), C.uintptr_t(_swig_i_8))
}

func (arg1 SwigcptrLibop) FindNearestPos(arg2 Wchar_t, arg3 int64, arg4 int64, arg5 int64, arg6 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	C._wrap_libop_FindNearestPos_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_10(_swig_i_2), C.swig_type_11(_swig_i_3), C.swig_type_12(_swig_i_4), C.uintptr_t(_swig_i_5))
}

func (arg1 SwigcptrLibop) EnumWindow(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 int64, arg6 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	C._wrap_libop_EnumWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_13(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_type_14(_swig_i_4), C.uintptr_t(_swig_i_5))
}

func (arg1 SwigcptrLibop) EnumWindowByProcess(arg2 Wchar_t, arg3 Wchar_t, arg4 Wchar_t, arg5 int64, arg6 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	C._wrap_libop_EnumWindowByProcess_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_type_15(_swig_i_4), C.uintptr_t(_swig_i_5))
}

func (arg1 SwigcptrLibop) EnumProcess(arg2 Wchar_t, arg3 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_libop_EnumProcess_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrLibop) ClientToScreen(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_ClientToScreen_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) FindWindow(arg2 Wchar_t, arg3 Wchar_t, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	C._wrap_libop_FindWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) FindWindowByProcess(arg2 Wchar_t, arg3 Wchar_t, arg4 Wchar_t, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	C._wrap_libop_FindWindowByProcess_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) FindWindowByProcessId(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	C._wrap_libop_FindWindowByProcessId_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_17(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) FindWindowEx(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	C._wrap_libop_FindWindowEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) GetClientRect(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64, arg6 *int64, arg7 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_libop_GetClientRect_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_19(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6))
}

func (arg1 SwigcptrLibop) GetClientSize(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_GetClientSize_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_20(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) GetForegroundFocus(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_GetForegroundFocus_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetForegroundWindow(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_GetForegroundWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetMousePointWindow(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_GetMousePointWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetPointWindow(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_GetPointWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_21(_swig_i_1), C.swig_type_22(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) GetProcessInfo(arg2 int64, arg3 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_libop_GetProcessInfo_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_23(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrLibop) GetSpecialWindow(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_GetSpecialWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_24(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) GetWindow(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_GetWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_25(_swig_i_1), C.swig_type_26(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) GetWindowClass(arg2 int64, arg3 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_libop_GetWindowClass_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_27(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrLibop) GetWindowProcessId(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_GetWindowProcessId_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_28(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) GetWindowProcessPath(arg2 int64, arg3 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_libop_GetWindowProcessPath_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_29(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrLibop) GetWindowRect(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64, arg6 *int64, arg7 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_libop_GetWindowRect_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_30(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6))
}

func (arg1 SwigcptrLibop) GetWindowState(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_GetWindowState_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_31(_swig_i_1), C.swig_type_32(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) GetWindowTitle(arg2 int64, arg3 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_libop_GetWindowTitle_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_33(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrLibop) MoveWindow(arg2 int64, arg3 int64, arg4 int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_MoveWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_34(_swig_i_1), C.swig_type_35(_swig_i_2), C.swig_type_36(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) ScreenToClient(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_ScreenToClient_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_37(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) SendPaste(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_SendPaste_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_38(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) SetClientSize(arg2 int64, arg3 int64, arg4 int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_SetClientSize_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_39(_swig_i_1), C.swig_type_40(_swig_i_2), C.swig_type_41(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) SetWindowState(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_SetWindowState_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_42(_swig_i_1), C.swig_type_43(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) SetWindowSize(arg2 int64, arg3 int64, arg4 int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_SetWindowSize_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_44(_swig_i_1), C.swig_type_45(_swig_i_2), C.swig_type_46(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) SetWindowText(arg2 int64, arg3 Wchar_t, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	C._wrap_libop_SetWindowText_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_47(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) SetWindowTransparent(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_SetWindowTransparent_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_48(_swig_i_1), C.swig_type_49(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) SendString(arg2 int64, arg3 Wchar_t, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	C._wrap_libop_SendString_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_50(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) SendStringIme(arg2 int64, arg3 Wchar_t, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	C._wrap_libop_SendStringIme_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_51(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) RunApp(arg2 Wchar_t, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_RunApp_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_52(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) WinExec(arg2 Wchar_t, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_WinExec_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_53(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) GetCmdStr(arg2 Wchar_t, arg3 int64, arg4 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_libop_GetCmdStr_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_type_54(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrLibop) BindWindow(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 Wchar_t, arg6 int64, arg7 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5.Swigcptr()
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_libop_BindWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_55(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.uintptr_t(_swig_i_4), C.swig_type_56(_swig_i_5), C.swig_voidp(_swig_i_6))
}

func (arg1 SwigcptrLibop) UnBindWindow(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_UnBindWindow_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetCursorPos(arg2 *int64, arg3 *int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_GetCursorPos_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) MoveR(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_MoveR_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_57(_swig_i_1), C.swig_type_58(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) MoveTo(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_MoveTo_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_59(_swig_i_1), C.swig_type_60(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) MoveToEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	C._wrap_libop_MoveToEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_61(_swig_i_1), C.swig_type_62(_swig_i_2), C.swig_type_63(_swig_i_3), C.swig_type_64(_swig_i_4), C.swig_voidp(_swig_i_5))
}

func (arg1 SwigcptrLibop) LeftClick(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_LeftClick_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) LeftDoubleClick(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_LeftDoubleClick_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) LeftDown(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_LeftDown_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) LeftUp(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_LeftUp_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) MiddleClick(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_MiddleClick_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) MiddleDown(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_MiddleDown_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) MiddleUp(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_MiddleUp_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) RightClick(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_RightClick_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) RightDown(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_RightDown_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) RightUp(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_RightUp_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) WheelDown(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_WheelDown_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) WheelUp(arg2 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_libop_WheelUp_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrLibop) GetKeyState(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_GetKeyState_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_65(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) KeyDown(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_KeyDown_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_66(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) KeyDownChar(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_KeyDownChar_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) KeyUp(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_KeyUp_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_67(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) KeyUpChar(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_KeyUpChar_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) WaitKey(arg2 int64, arg3 int64, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_libop_WaitKey_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_68(_swig_i_1), C.swig_type_69(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) KeyPress(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_KeyPress_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_70(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) KeyPressChar(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_KeyPressChar_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) Capture(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	C._wrap_libop_Capture_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_71(_swig_i_1), C.swig_type_72(_swig_i_2), C.swig_type_73(_swig_i_3), C.swig_type_74(_swig_i_4), C.uintptr_t(_swig_i_5), C.swig_voidp(_swig_i_6))
}

func (arg1 SwigcptrLibop) CmpColor(arg2 int64, arg3 int64, arg4 Wchar_t, arg5 float64, arg6 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	C._wrap_libop_CmpColor_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_75(_swig_i_1), C.swig_type_76(_swig_i_2), C.uintptr_t(_swig_i_3), C.double(_swig_i_4), C.swig_voidp(_swig_i_5))
}

func (arg1 SwigcptrLibop) FindColor(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 *int64, arg10 *int64, arg11 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	C._wrap_libop_FindColor_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_77(_swig_i_1), C.swig_type_78(_swig_i_2), C.swig_type_79(_swig_i_3), C.swig_type_80(_swig_i_4), C.uintptr_t(_swig_i_5), C.double(_swig_i_6), C.swig_type_81(_swig_i_7), C.swig_voidp(_swig_i_8), C.swig_voidp(_swig_i_9), C.swig_voidp(_swig_i_10))
}

func (arg1 SwigcptrLibop) FindColorEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9.Swigcptr()
	C._wrap_libop_FindColorEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_82(_swig_i_1), C.swig_type_83(_swig_i_2), C.swig_type_84(_swig_i_3), C.swig_type_85(_swig_i_4), C.uintptr_t(_swig_i_5), C.double(_swig_i_6), C.swig_type_86(_swig_i_7), C.uintptr_t(_swig_i_8))
}

func (arg1 SwigcptrLibop) FindMultiColor(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 *int64, arg11 *int64, arg12 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7.Swigcptr()
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	C._wrap_libop_FindMultiColor_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_87(_swig_i_1), C.swig_type_88(_swig_i_2), C.swig_type_89(_swig_i_3), C.swig_type_90(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.double(_swig_i_7), C.swig_type_91(_swig_i_8), C.swig_voidp(_swig_i_9), C.swig_voidp(_swig_i_10), C.swig_voidp(_swig_i_11))
}

func (arg1 SwigcptrLibop) FindMultiColorEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7.Swigcptr()
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10.Swigcptr()
	C._wrap_libop_FindMultiColorEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_92(_swig_i_1), C.swig_type_93(_swig_i_2), C.swig_type_94(_swig_i_3), C.swig_type_95(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.double(_swig_i_7), C.swig_type_96(_swig_i_8), C.uintptr_t(_swig_i_9))
}

func (arg1 SwigcptrLibop) FindPic(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 *int64, arg11 *int64, arg12 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7.Swigcptr()
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	C._wrap_libop_FindPic_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_97(_swig_i_1), C.swig_type_98(_swig_i_2), C.swig_type_99(_swig_i_3), C.swig_type_100(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.double(_swig_i_7), C.swig_type_101(_swig_i_8), C.swig_voidp(_swig_i_9), C.swig_voidp(_swig_i_10), C.swig_voidp(_swig_i_11))
}

func (arg1 SwigcptrLibop) FindPicEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7.Swigcptr()
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10.Swigcptr()
	C._wrap_libop_FindPicEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_102(_swig_i_1), C.swig_type_103(_swig_i_2), C.swig_type_104(_swig_i_3), C.swig_type_105(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.double(_swig_i_7), C.swig_type_106(_swig_i_8), C.uintptr_t(_swig_i_9))
}

func (arg1 SwigcptrLibop) FindPicExS(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7.Swigcptr()
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10.Swigcptr()
	C._wrap_libop_FindPicExS_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_107(_swig_i_1), C.swig_type_108(_swig_i_2), C.swig_type_109(_swig_i_3), C.swig_type_110(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.double(_swig_i_7), C.swig_type_111(_swig_i_8), C.uintptr_t(_swig_i_9))
}

func (arg1 SwigcptrLibop) FindColorBlock(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 int64, arg10 int64, arg11 *int64, arg12 *int64, arg13 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	_swig_i_11 := arg12
	_swig_i_12 := arg13
	C._wrap_libop_FindColorBlock_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_112(_swig_i_1), C.swig_type_113(_swig_i_2), C.swig_type_114(_swig_i_3), C.swig_type_115(_swig_i_4), C.uintptr_t(_swig_i_5), C.double(_swig_i_6), C.swig_type_116(_swig_i_7), C.swig_type_117(_swig_i_8), C.swig_type_118(_swig_i_9), C.swig_voidp(_swig_i_10), C.swig_voidp(_swig_i_11), C.swig_voidp(_swig_i_12))
}

func (arg1 SwigcptrLibop) FindColorBlockEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 int64, arg10 int64, arg11 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11.Swigcptr()
	C._wrap_libop_FindColorBlockEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_119(_swig_i_1), C.swig_type_120(_swig_i_2), C.swig_type_121(_swig_i_3), C.swig_type_122(_swig_i_4), C.uintptr_t(_swig_i_5), C.double(_swig_i_6), C.swig_type_123(_swig_i_7), C.swig_type_124(_swig_i_8), C.swig_type_125(_swig_i_9), C.uintptr_t(_swig_i_10))
}

func (arg1 SwigcptrLibop) GetColor(arg2 int64, arg3 int64, arg4 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_libop_GetColor_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_126(_swig_i_1), C.swig_type_127(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrLibop) SetDisplayInput(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_SetDisplayInput_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) LoadPic(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_LoadPic_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) FreePic(arg2 Wchar_t, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_libop_FreePic_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) LoadMemPic(arg2 Wchar_t, arg3 uintptr, arg4 int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_LoadMemPic_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_128(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) GetScreenData(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 *uintptr, arg7 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	C._wrap_libop_GetScreenData_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_129(_swig_i_1), C.swig_type_130(_swig_i_2), C.swig_type_131(_swig_i_3), C.swig_type_132(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6))
}

func (arg1 SwigcptrLibop) GetScreenDataBmp(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 *uintptr, arg7 *int64, arg8 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	C._wrap_libop_GetScreenDataBmp_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_133(_swig_i_1), C.swig_type_134(_swig_i_2), C.swig_type_135(_swig_i_3), C.swig_type_136(_swig_i_4), C.swig_voidp(_swig_i_5), C.swig_voidp(_swig_i_6), C.swig_voidp(_swig_i_7))
}

func (arg1 SwigcptrLibop) GetScreenFrameInfo(arg2 *int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_GetScreenFrameInfo_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) MatchPicName(arg2 Wchar_t, arg3 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_libop_MatchPicName_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func (arg1 SwigcptrLibop) SetDict(arg2 int64, arg3 Wchar_t, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	C._wrap_libop_SetDict_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_137(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrLibop) SetMemDict(arg2 int64, arg3 Wchar_t, arg4 int64, arg5 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_libop_SetMemDict_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_138(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_139(_swig_i_3), C.swig_voidp(_swig_i_4))
}

func (arg1 SwigcptrLibop) UseDict(arg2 int64, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_libop_UseDict_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_140(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrLibop) Ocr(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8.Swigcptr()
	C._wrap_libop_Ocr_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_141(_swig_i_1), C.swig_type_142(_swig_i_2), C.swig_type_143(_swig_i_3), C.swig_type_144(_swig_i_4), C.uintptr_t(_swig_i_5), C.double(_swig_i_6), C.uintptr_t(_swig_i_7))
}

func (arg1 SwigcptrLibop) OcrEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8.Swigcptr()
	C._wrap_libop_OcrEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_145(_swig_i_1), C.swig_type_146(_swig_i_2), C.swig_type_147(_swig_i_3), C.swig_type_148(_swig_i_4), C.uintptr_t(_swig_i_5), C.double(_swig_i_6), C.uintptr_t(_swig_i_7))
}

func (arg1 SwigcptrLibop) FindStr(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 *int64, arg10 *int64, arg11 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7.Swigcptr()
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	_swig_i_10 := arg11
	C._wrap_libop_FindStr_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_149(_swig_i_1), C.swig_type_150(_swig_i_2), C.swig_type_151(_swig_i_3), C.swig_type_152(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.double(_swig_i_7), C.swig_voidp(_swig_i_8), C.swig_voidp(_swig_i_9), C.swig_voidp(_swig_i_10))
}

func (arg1 SwigcptrLibop) FindStrEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7.Swigcptr()
	_swig_i_7 := arg8
	_swig_i_8 := arg9.Swigcptr()
	C._wrap_libop_FindStrEx_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_153(_swig_i_1), C.swig_type_154(_swig_i_2), C.swig_type_155(_swig_i_3), C.swig_type_156(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.double(_swig_i_7), C.uintptr_t(_swig_i_8))
}

func (arg1 SwigcptrLibop) OcrAuto(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 float64, arg7 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7.Swigcptr()
	C._wrap_libop_OcrAuto_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_157(_swig_i_1), C.swig_type_158(_swig_i_2), C.swig_type_159(_swig_i_3), C.swig_type_160(_swig_i_4), C.double(_swig_i_5), C.uintptr_t(_swig_i_6))
}

func (arg1 SwigcptrLibop) OcrFromFile(arg2 Wchar_t, arg3 Wchar_t, arg4 float64, arg5 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	C._wrap_libop_OcrFromFile_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2), C.double(_swig_i_3), C.uintptr_t(_swig_i_4))
}

func (arg1 SwigcptrLibop) OcrAutoFromFile(arg2 Wchar_t, arg3 float64, arg4 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4.Swigcptr()
	C._wrap_libop_OcrAutoFromFile_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.double(_swig_i_2), C.uintptr_t(_swig_i_3))
}

func (arg1 SwigcptrLibop) FindLine(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8.Swigcptr()
	C._wrap_libop_FindLine_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_161(_swig_i_1), C.swig_type_162(_swig_i_2), C.swig_type_163(_swig_i_3), C.swig_type_164(_swig_i_4), C.uintptr_t(_swig_i_5), C.double(_swig_i_6), C.uintptr_t(_swig_i_7))
}

func (arg1 SwigcptrLibop) WriteData(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 int64, arg6 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	C._wrap_libop_WriteData_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_165(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_type_166(_swig_i_4), C.swig_voidp(_swig_i_5))
}

func (arg1 SwigcptrLibop) ReadData(arg2 int64, arg3 Wchar_t, arg4 int64, arg5 Std_wstring) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	C._wrap_libop_ReadData_opEx_7bb69c4307a7cd11(C.uintptr_t(_swig_i_0), C.swig_type_167(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_type_168(_swig_i_3), C.uintptr_t(_swig_i_4))
}

type Libop interface {
	Swigcptr() uintptr
	SwigIsLibop()
	Ver() (_swig_ret Std_wstring)
	SetPath(arg2 Wchar_t, arg3 *int64)
	GetPath(arg2 Std_wstring)
	GetBasePath(arg2 Std_wstring)
	GetID(arg2 *int64)
	GetLastError(arg2 *int64)
	SetShowErrorMsg(arg2 int64, arg3 *int64)
	Sleep(arg2 int64, arg3 *int64)
	InjectDll(arg2 Wchar_t, arg3 Wchar_t, arg4 *int64)
	EnablePicCache(arg2 int64, arg3 *int64)
	CapturePre(arg2 Wchar_t, arg3 *int64)
	AStarFindPath(arg2 int64, arg3 int64, arg4 Wchar_t, arg5 int64, arg6 int64, arg7 int64, arg8 int64, arg9 Std_wstring)
	FindNearestPos(arg2 Wchar_t, arg3 int64, arg4 int64, arg5 int64, arg6 Std_wstring)
	EnumWindow(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 int64, arg6 Std_wstring)
	EnumWindowByProcess(arg2 Wchar_t, arg3 Wchar_t, arg4 Wchar_t, arg5 int64, arg6 Std_wstring)
	EnumProcess(arg2 Wchar_t, arg3 Std_wstring)
	ClientToScreen(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64)
	FindWindow(arg2 Wchar_t, arg3 Wchar_t, arg4 *int64)
	FindWindowByProcess(arg2 Wchar_t, arg3 Wchar_t, arg4 Wchar_t, arg5 *int64)
	FindWindowByProcessId(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 *int64)
	FindWindowEx(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 *int64)
	GetClientRect(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64, arg6 *int64, arg7 *int64)
	GetClientSize(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64)
	GetForegroundFocus(arg2 *int64)
	GetForegroundWindow(arg2 *int64)
	GetMousePointWindow(arg2 *int64)
	GetPointWindow(arg2 int64, arg3 int64, arg4 *int64)
	GetProcessInfo(arg2 int64, arg3 Std_wstring)
	GetSpecialWindow(arg2 int64, arg3 *int64)
	GetWindow(arg2 int64, arg3 int64, arg4 *int64)
	GetWindowClass(arg2 int64, arg3 Std_wstring)
	GetWindowProcessId(arg2 int64, arg3 *int64)
	GetWindowProcessPath(arg2 int64, arg3 Std_wstring)
	GetWindowRect(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64, arg6 *int64, arg7 *int64)
	GetWindowState(arg2 int64, arg3 int64, arg4 *int64)
	GetWindowTitle(arg2 int64, arg3 Std_wstring)
	MoveWindow(arg2 int64, arg3 int64, arg4 int64, arg5 *int64)
	ScreenToClient(arg2 int64, arg3 *int64, arg4 *int64, arg5 *int64)
	SendPaste(arg2 int64, arg3 *int64)
	SetClientSize(arg2 int64, arg3 int64, arg4 int64, arg5 *int64)
	SetWindowState(arg2 int64, arg3 int64, arg4 *int64)
	SetWindowSize(arg2 int64, arg3 int64, arg4 int64, arg5 *int64)
	SetWindowText(arg2 int64, arg3 Wchar_t, arg4 *int64)
	SetWindowTransparent(arg2 int64, arg3 int64, arg4 *int64)
	SendString(arg2 int64, arg3 Wchar_t, arg4 *int64)
	SendStringIme(arg2 int64, arg3 Wchar_t, arg4 *int64)
	RunApp(arg2 Wchar_t, arg3 int64, arg4 *int64)
	WinExec(arg2 Wchar_t, arg3 int64, arg4 *int64)
	GetCmdStr(arg2 Wchar_t, arg3 int64, arg4 Std_wstring)
	BindWindow(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 Wchar_t, arg6 int64, arg7 *int64)
	UnBindWindow(arg2 *int64)
	GetCursorPos(arg2 *int64, arg3 *int64, arg4 *int64)
	MoveR(arg2 int64, arg3 int64, arg4 *int64)
	MoveTo(arg2 int64, arg3 int64, arg4 *int64)
	MoveToEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 *int64)
	LeftClick(arg2 *int64)
	LeftDoubleClick(arg2 *int64)
	LeftDown(arg2 *int64)
	LeftUp(arg2 *int64)
	MiddleClick(arg2 *int64)
	MiddleDown(arg2 *int64)
	MiddleUp(arg2 *int64)
	RightClick(arg2 *int64)
	RightDown(arg2 *int64)
	RightUp(arg2 *int64)
	WheelDown(arg2 *int64)
	WheelUp(arg2 *int64)
	GetKeyState(arg2 int64, arg3 *int64)
	KeyDown(arg2 int64, arg3 *int64)
	KeyDownChar(arg2 Wchar_t, arg3 *int64)
	KeyUp(arg2 int64, arg3 *int64)
	KeyUpChar(arg2 Wchar_t, arg3 *int64)
	WaitKey(arg2 int64, arg3 int64, arg4 *int64)
	KeyPress(arg2 int64, arg3 *int64)
	KeyPressChar(arg2 Wchar_t, arg3 *int64)
	Capture(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 *int64)
	CmpColor(arg2 int64, arg3 int64, arg4 Wchar_t, arg5 float64, arg6 *int64)
	FindColor(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 *int64, arg10 *int64, arg11 *int64)
	FindColorEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 Std_wstring)
	FindMultiColor(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 *int64, arg11 *int64, arg12 *int64)
	FindMultiColorEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 Std_wstring)
	FindPic(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 *int64, arg11 *int64, arg12 *int64)
	FindPicEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 Std_wstring)
	FindPicExS(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 int64, arg10 Std_wstring)
	FindColorBlock(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 int64, arg10 int64, arg11 *int64, arg12 *int64, arg13 *int64)
	FindColorBlockEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 int64, arg9 int64, arg10 int64, arg11 Std_wstring)
	GetColor(arg2 int64, arg3 int64, arg4 Std_wstring)
	SetDisplayInput(arg2 Wchar_t, arg3 *int64)
	LoadPic(arg2 Wchar_t, arg3 *int64)
	FreePic(arg2 Wchar_t, arg3 *int64)
	LoadMemPic(arg2 Wchar_t, arg3 uintptr, arg4 int64, arg5 *int64)
	GetScreenData(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 *uintptr, arg7 *int64)
	GetScreenDataBmp(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 *uintptr, arg7 *int64, arg8 *int64)
	GetScreenFrameInfo(arg2 *int64, arg3 *int64)
	MatchPicName(arg2 Wchar_t, arg3 Std_wstring)
	SetDict(arg2 int64, arg3 Wchar_t, arg4 *int64)
	SetMemDict(arg2 int64, arg3 Wchar_t, arg4 int64, arg5 *int64)
	UseDict(arg2 int64, arg3 *int64)
	Ocr(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 Std_wstring)
	OcrEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 Std_wstring)
	FindStr(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 *int64, arg10 *int64, arg11 *int64)
	FindStrEx(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 Wchar_t, arg8 float64, arg9 Std_wstring)
	OcrAuto(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 float64, arg7 Std_wstring)
	OcrFromFile(arg2 Wchar_t, arg3 Wchar_t, arg4 float64, arg5 Std_wstring)
	OcrAutoFromFile(arg2 Wchar_t, arg3 float64, arg4 Std_wstring)
	FindLine(arg2 int64, arg3 int64, arg4 int64, arg5 int64, arg6 Wchar_t, arg7 float64, arg8 Std_wstring)
	WriteData(arg2 int64, arg3 Wchar_t, arg4 Wchar_t, arg5 int64, arg6 *int64)
	ReadData(arg2 int64, arg3 Wchar_t, arg4 int64, arg5 Std_wstring)
}


type SwigcptrStd_wstring uintptr
type Std_wstring interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_wstring) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrWchar_t uintptr
type Wchar_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrWchar_t) Swigcptr() uintptr {
	return uintptr(p)
}

